services:
  site:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "9080:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3307"
    environment:
      MYSQL_DATABASE: subscribers_api
      MYSQL_USER: mjbaga
      MYSQL_PASSWORD: USS@3nterprise
      MYSQL_ROOT_PASSWORD: USS@3nterprise
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9081:80'
    environment:
      UPLOAD_LIMIT: 1024M
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
